steps:
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - functions
    - deploy
    - load-data-bigquery
    - --gen2
    - --runtime=python312
    - --source=.
    - --entry-point=load_data_bigquery

options:
  logging: CLOUD_LOGGING_ONLY
